using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using dotnetapp.Models;
using dotnetapp.Services;

namespace dotnetapp.Controllers
{
    [ApiController]
    [Route("api")]
    public class AuthenticationController : ControllerBase
    {
        private readonly IAuthService _authService;

        public AuthenticationController(IAuthService authService)
        {
            _authService = authService;
        }

        // Login Endpoint
        [HttpPost("login")]
        public async Task<IActionResult> Login(LoginModel model)
        {
            try
            {
                var result = await _authService.Login(model);
                if (result.Item1 == 0)
                    return BadRequest(new { Status = "Error", Message = result.Item2 });

                return Ok(new { Status = "Success", token = result.Item2 });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { Status = "Error", Message = ex.Message });
            }
        }

        // Register Endpoint
        [HttpPost("register")]
        public async Task<IActionResult> Register(User model)
        {
            try
            {
                if (model.UserId != 0)
                    return BadRequest(new { Status = "Error", Message = "UserId should not be provided. It is auto-generated by the system." });

                var result = await _authService.Registration(model, model.UserRole);
                if (result.Item1 == 0)
                    return BadRequest(new { Status = "Error", Message = result.Item2 });

                return Ok(new { Status = "Success", Message = result.Item2 });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { Status = "Error", Message = ex.Message });
            }
        }
    }
}
